### ISSUE TITLE
[Feature request] Use side mouse buttons for Prev / Next navigation

### ISSUE THREAD

**Issue by Michoko92** [acoppes/unity-history-window#27]
Hi,

Nice little extension, thank you very much for sharing. Do you think it would be possible to add previous / next navigation through side mouse buttons, like in a browser? It would be super handy! :)

Thank you and happy new year!

**Comment by acoppes** [comment]
Do you know if those buttons can be mapped with Unity new hotkeys/shortcuts? I can try to make those actions configurable by shortcuts and then you should be able to map it to whatever you want.

Also, if you know how to do it and want to submit a pull request, I will be super happy to merge it.

**Comment by Team-on** [comment]
I think that you need Mouse3 and Mouse4 for that
https://docs.unity3d.com/ScriptReference/KeyCode.html?_ga=2.113213380.1118728693.1609617326-741310434.1607024629
![image](https://user-images.githubusercontent.com/30273693/103465545-53444f80-4d45-11eb-92b5-7b14f75ab2b7.png)

**Comment by acoppes** [comment]
Added shortcuts but can't configure mouse buttons through the shortcuts manager and if I configure by default Mouse3 o Mouse4 it breaks the shortcuts manager (already reported a bug there). 

So, I was trying by implementing in the OnGUI but I am not getting any mouse events using the code suggested in the link: 

```
if (Event.current.Equals(Event.KeyboardEvent(KeyCode.Mouse3.ToString())))
{
	Debug.Log("Mouse 3 was pressed.");
}
```

Maybe it is my mouse but I suppose it doesn't work using keyboard events, or maybe my mouse buttons are not turned on. Tried also:

```
if (Event.current.type == EventType.MouseUp)
{
	Debug.Log($"Mouse {Event.current.button} was pressed.");
}
```

But not getting any event for my extra mouse buttons, also, when getting events for the normal buttons, it only appear when focusing on the Selection History window since we are using OnGUI().

So, my suggestions are a) map your mouse buttons to special keyboard shortcuts in your mouse configuration and map those shortcuts in the Unity Shortcuts, b) check if you can implement it yourself, even if you have to create custom code in OnGUI, and send a pull request, I will check it and merge, c) wait for Unity, maybe they decide to allow extra mouse buttons shortcuts in the shortcuts window.

**Comment by acoppes** [comment]
For example, I used my razer synapse to link shortcuts to my buttons, it can even be customized by app I believe (so you can use it this way in unity only).

![shortcuts](https://user-images.githubusercontent.com/591852/103466231-da7fcc00-4d21-11eb-9f86-b5782d4edd54.png)

And it worked pretty fine. It is a bit absolute in my opinion since it would be great that different Unity tools/plugins allow to customize this buttons differently but following this approach is all or nothing.

**Comment by Michoko92** [comment]
Thank you for looking into this issue. I have a Razer mouse myself, and could indeed proceed as you suggested. But then I'd lose the back / forth feature in all other applications I use (especially the windows file explorer or web browser).

I wish I would have enough experience with Unity to help with this, but I'm still a beginner, and don't know how to solve this. However, if it can help, I'm aware of at least one asset that seems to handle mouse buttons nicely: https://assetstore.unity.com/packages/tools/utilities/back-button-50892 . Maybe it will help.

**Comment by acoppes** [comment]
I believe that you can link a custom mouse mapping to an specific application with the razor Link Program option, you have to create a profile like "Unity Developer" or something you want, and customize it as you want, then link it to Unity editor executable. Then, I believe synapse will automatically pick your custom profile when using unity and go back to default when using another app.

**Comment by Michoko92** [comment]
It works, thank you!

**Comment by LucasJonesXR** [comment]
Thank you! Just what I was after :)
