### ISSUE TITLE
Highlight not working in Unity 6

### ISSUE THREAD

**Issue by hsandt** [acoppes/unity-history-window#53]
I think highlight asset on click used to work before? Now it opens the containing folder but for some reason stopped highlighting the asset, making it harder to locate.

**Comment by acoppes** [comment]
Thanks for reporting it, not sure if it is an issue related with the change of adding the open folder with double click capability (and unity 6). You still can highlight with right click or with magnifier icon I believe, that should be working since it uses editor ping utility. I have to test everything with Unity 6.

**Comment by acoppes** [comment]
Ok, tested in latest Unity 6 and it is working, just have to use right click and/or the icon.
